export const products = [
  {
    _id: 19691562626688221398263086783120406706,
    additional_image:
      "https://staticimg.titan.co.in/Tanishq/Catalog/502998SBHAAA04_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 0,
    brand: "Tanishq",
    business_unit: "Jewellery",
    category: "",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573651855000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Tanishq 18KT Gold and Diamond Stud Earrings",
    diamond_clarity: "VS",
    diamond_color: "DIA G H COLGRE",
    diamond_cut: "",
    discount_percentage: 0,
    expiration_date: "NA",
    full_description:
      "These stud earrings are the perfect finishing touch for your everyday style. Its petite elegance is sure to leave everyone charmed.",
    gemstone1: "Synthetic|2|String||",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 18,
    google_product_category: "Apparel & Accessories > Jewelry",
    gtin: "",
    height: "",
    id: "502998SBHAAA042JA000003",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Tanishq/Catalog/502998SBHAAA04_1.jpg",
    item_group_id: "502998SBHAAA04_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery with Stones",
    last_modified_on: 1573960742000,
    listprice: 4431,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "502998SBHAAA04",
    mpn: "502998SBHAAA042JA000003",
    name: "18KT Gold and Diamond Stud Earrings",
    occasion: "Work",
    out_of_shelf: true,
    price: 4431,
    price_usd: 61.42,
    product: "STUD EARRING",
    product_type: "Home > Jeweller",
    sale_price_usd: 61.42,
    status: "Active",
    sub_account: "[tanishq]",
    subcategories: "Jeweller",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/tanishq-18kt-gold-and-diamond-stud-earrings-502998sbhaaa04",
    variants: "{u'2JA000003': {u'price': 4431.0, u'listprice': 4431.0}}",
    width: "",
  },
  {
    _id: 94503287366179615906786364787727986888,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819GAHAACZ_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-collections",
    collection: "Mia Birthstone Pendants",
    color: "",
    condition: "NEW",
    created_on: 1573824234000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Mia by Tanishq Scorpio 14KT Rose Gold Pendant and Chain",
    diamond_clarity: "",
    diamond_color: "",
    diamond_cut: "",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "Wrap yourself in an aura of mystery with this elegant piece of jewellery. An exquisite rose pendant on a petite rose gold chain is adorned with bright yellow stones. Pamper the passionate and assertive Scorpio in you with this stylish jewellery.",
    gemstone1: "Cubic Zirconia|2|NA|NA|Round",
    gemstone2: "Cubic Zirconia|1|NA|NA|Round",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "310 mm",
    id: "552819GAHAAACZ2BD000278",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819GAHAACZ_1.jpg",
    item_group_id: "552819GAHAACZ_P",
    jew_size: "30.48 cm",
    jewellery_type: "Gemstone Jewellery",
    last_modified_on: 1576986564000,
    listprice: 16999,
    metal: "Gold",
    metal_color: "Rose Gold",
    mfr_code: "552819GAHAAACZ",
    mpn: "552819GAHAAACZ2BD000278",
    name: "Mia by Tanishq Scorpio 14KT Rose Gold Pendant and Chain",
    occasion: "Daily Wear",
    out_of_shelf: false,
    price: 16149,
    price_usd: 239.02,
    product: "Chain + Pendant",
    product_type: "Home > Jewellery",
    sale_price_usd: 227.07,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: 1,
    unit: "millimeters",
    updated: false,
    url: "/product/chain-pendant-552819gahaacz",
    variants:
      "{u'2BD000278': {u'price': 16149.0, u'listprice': 16999.0}, u'2BD000277': {u'price': 16149.0, u'listprice': 16999.0}}",
    width: "",
  },
  {
    _id: 69101243338530276119601955414893494127,
    additional_image:
      "https://staticimg.titan.co.in/Tanishq/Catalog/502999FSZAA02_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "Tanishq",
    business_unit: "Jewellery",
    category: "",
    collection: "Contemporary",
    color: "",
    condition: "NEW",
    created_on: 1574255924000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Tanishq 18KT Rose Gold and Diamond Finger Ring",
    diamond_clarity: "SI2",
    diamond_color: "GH",
    diamond_cut: "",
    discount_percentage: 0,
    expiration_date: "NA",
    full_description:
      "Cast in rose gold and crafted in mdoern design, this ring is simply stunning. It is an ideal match for those classy occasion outfits.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 18,
    google_product_category: "Apparel & Accessories >\tJewelry > Rings ",
    gtin: "",
    height: "",
    id: "502999FSZLAA022JA005106",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Tanishq/Catalog/502999FSZAA02_1.jpg",
    item_group_id: "502999FSZAA02_P",
    jew_size: "16.40 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576920518000,
    listprice: 10988,
    metal: "Gold",
    metal_color: "Rose",
    mfr_code: "502999FSZLAA02",
    mpn: "502999FSZLAA022JA005106",
    name: "18KT Rose Gold and Diamond Finger Ring",
    occasion: "",
    out_of_shelf: false,
    price: 10988,
    price_usd: 161.21,
    product: "FINGER RING",
    product_type: "Home > Diamond",
    sale_price_usd: 161.21,
    status: "Active",
    sub_account: "[tanishq]",
    subcategories: "Diamond",
    trendrank: null,
    unit: "",
    updated: false,
    url:
      "/product/tanishq-18kt-rose-gold-and-diamond-finger-ring-502999fszaa02",
    variants:
      "{u'2JA005106': {u'price': 11493.0, u'listprice': 11493.0}, u'2JA005105': {u'price': 10988.0, u'listprice': 10988.0}}",
    width: "16.4 mm",
  },
  {
    _id: 111190756107460279780897264511128671073,
    additional_image:
      "https://staticimg.titan.co.in/Tanishq/Catalog/505001SDWAGA09_1.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "Tanishq",
    business_unit: "Jewellery",
    category: "",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1574328084000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Tanishq 18KT Gold and Diamond Earrings for Women",
    diamond_clarity: "I1 I2",
    diamond_color: "DIA   G H   COL GREY",
    diamond_cut: "",
    discount_percentage: 0,
    expiration_date: "NA",
    full_description:
      "This classic design of these stud earrings makes it the perfect choice for daily wear. It easily complements western as well as ethnic ensembles!",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 18,
    google_product_category: "Apparel & Accessories > Jewelry",
    gtin: "",
    height: "",
    id: "505001SDWAGA092BD005443",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Tanishq/Catalog/505001SDWAGA09_1.jpg",
    item_group_id: "505001SDWAGA09_P",
    jew_size: "",
    jewellery_type: "Studs",
    last_modified_on: 1576825236000,
    listprice: 7688,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "505001SDWAGA09",
    mpn: "505001SDWAGA092BD005443",
    name: "18KT Gold and Diamond Earrings",
    occasion: "Daily Wear",
    out_of_shelf: false,
    price: 7688,
    price_usd: 107.84,
    product: "STUD EARRING",
    product_type: "Home > Jeweller",
    sale_price_usd: 107.84,
    status: "Active",
    sub_account: "[tanishq]",
    subcategories: "Jeweller",
    trendrank: 30,
    unit: "",
    updated: false,
    url:
      "/product/tanishq-18kt-gold-and-diamond-earrings-for-women-505001sdwaga09",
    variants: "{u'2BD005443': {u'price': 7688.0, u'listprice': 7688.0}}",
    width: "",
  },
  {
    _id: 322967103574146053037517469114406589845,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819FRUAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Collections",
    collection: "Smolitaires",
    color: "",
    condition: "NEW",
    created_on: 1573539966000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq 14KT White Gold Ring for Women in Modern Design",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "White Gold Ring - This ring has a lovely 14KT white gold finish that looks luxuriously shiny. Diamond studded Design - The white gold appeal of this Mia Tanishq jewellery is embellished by a round cut diamond in the crown. Fashionably Detailed - Meant for the modern day women, this ring is detailed with soft waves for a fashionable look. Comfortable to Wear - Smooth at touch, the diamond ring slides in and out of the finger without causing discomfort. Versatile in Appeal - This 14KT gold ring with a solitaire can be worn with any outfit in your wardrobe. Crafted in 14KT white gold, this fine gold diamond ring flaunts a modern appeal with a fancy detail of wavy curves near the crown. It comes studded with a round cut, diamond to boast a conspicuous sparkle. This finger ring for women can be worn as a single accessory or with similar slender rings to create two completely different looks. The ring has an understated design for a simple everyday appeal. It can be worn with formal or informal outfits. This ring is a perfect gift for women. Mia by Tanishq brings another collection of modern jewellery in versatile ethno contemporary designs that complete both, formal and informal looks. They are meant for the modern women who are powerful, strong, and charming. All the designs are crafted niftily in 14KT gold, making the articles in Smolitaire Collection dazzling, easy to care, and lighter on the pocket.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "21.8 mm",
    id: "552819FRULAA222BD000004",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819FRUAA22_1.jpg",
    item_group_id: "552819FRUAA22_P",
    jew_size: "16.40 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986548000,
    listprice: 19999,
    metal: "Gold",
    metal_color: "yellow",
    mfr_code: "552819FRULAA22",
    mpn: "552819FRULAA222BD000004",
    name: "Mia by Tanishq 14KT White Gold Ring for Women in Modern Design",
    occasion: "",
    out_of_shelf: false,
    price: 18999,
    price_usd: 281.2,
    product: "FINGER RING",
    product_type: "Home > Collections > Smolitaires",
    sale_price_usd: 267.14,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Smolitaires",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-552819fruaa22",
    variants: "{u'2BD000004': {u'price': 18999.0, u'listprice': 19999.0}}",
    width: "20.23 mm",
  },
  {
    _id: 334628595086126603013856999144225670603,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819FRTAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Collections",
    collection: "Smolitaires",
    color: "",
    condition: "NEW",
    created_on: 1573539966000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq 14KT Yellow Gold Ring for Women in Bow and Hearts Design",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "Gold Diamond Ring - The ring flaunts 14K yellow gold finish and a round cut solitaire in the crown. Luxurious but Non flashy - Although, the ring has opulent details, its simple design looks modest. Feminine Appeal - Detailed with a cut out bow like design and two hearts on its sides, this diamond ring highlights the youthful and feminine appeal. Everyday Design - The slender band and understated design make the ring an apt jewellery piece to wear in office, small social gatherings, and casual dinner nights. Mia Tanishq Jewellery - This ring is a part of the latest Smolitaire Collection of Mia by Tanishq. This ring is a lovely piece of jewellery that mirrors your youthful and loving personality. Embellishing the 14KT yellow gold band of this ladies ring is the round cut diamond set inside the crown. Emphasising its slender silhouette and feminine design are the heart and bow shaped cutouts. The smooth finish of this gold ring lets you glide it in and out of the finger with ease. It can be worn with a saree or a maxi dress and the ring will complement both the dresses with equal grace. Mia by Tanishq brings another collection of modern jewellery in versatile ethno contemporary designs that complete both, formal and informal looks. They are meant for the modern women who are powerful, strong, and charming. All the designs are crafted niftily in 14KT gold, making the articles in Smolitaire Collection dazzling, easy to care, and lighter on the pocket.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "21.77 mm",
    id: "552819FRTMAA222BD000040",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819FRTAA22_1.jpg",
    item_group_id: "552819FRTAA22_P",
    jew_size: "16.80 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986577000,
    listprice: 16999,
    metal: "Gold",
    metal_color: "yellow",
    mfr_code: "552819FRTMAA22",
    mpn: "552819FRTMAA222BD000040",
    name:
      "Mia by Tanishq 14KT Yellow Gold Ring for Women in Bow and Hearts Design",
    occasion: "",
    out_of_shelf: false,
    price: 16149,
    price_usd: 239.02,
    product: "FINGER RING",
    product_type: "Home > Collections > Smolitaires",
    sale_price_usd: 227.07,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Smolitaires",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-552819frtaa22",
    variants:
      "{u'2BD000035': {u'price': 16149.0, u'listprice': 16999.0}, u'2BD000040': {u'price': 16149.0, u'listprice': 16999.0}}",
    width: "19.9 mm",
  },
  {
    _id: 86465604859656008349448143555362752294,
    additional_image:
      "https://staticimg.titan.co.in/Tanishq/Catalog/502014SGKAGA32_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "Tanishq",
    business_unit: "Jewellery",
    category: "",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573539966000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Tanishq 18KT Yellow Gold Diamond and Tsavorite Stud Earrings with Paisley Design",
    diamond_clarity: "SI2",
    diamond_color: "GH",
    diamond_cut: "",
    discount_percentage: 0,
    expiration_date: "NA",
    full_description:
      "This pair of 18KT yellow gold stud earrings showcases two pear-cut tsavorite stones and ten round brilliant cut diamonds of G-H colour and SI2 clarity grade. The stud earrings showcase a paisley design. The paisley motif is arranged in an inverted fashion and is pave-set with diamonds on the upper partially rhodium-plated section. Highlighting the centre of the stud earrings are pear-cut tsavorite stones, secured in three-prong settings. The colour combination of the stones and the paisley design accentuate the unique design of these earrings. Ensuring comfort to the wearer, these high-polished earrings are fitted with screw posts and secured by baby Bombay screw closures.",
    gemstone1: "Emerald|2|Prong|NA|Pear",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 18,
    google_product_category: "Apparel & Accessories > Jewelry",
    gtin: "",
    height: "",
    id: "502014SGKAGA322JA005103",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Tanishq/Catalog/502014SGKAGA32_1.jpg",
    item_group_id: "502014SGKAGA32_P",
    jew_size: "",
    jewellery_type: "Studs",
    last_modified_on: 1576920570000,
    listprice: 15918,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "502014SGKAGA32",
    mpn: "502014SGKAGA322JA005103",
    name: "18KT Diamond and Tsavorite Paisley Studs",
    occasion: "",
    out_of_shelf: false,
    price: 15918,
    price_usd: 224.3,
    product: "STUD EARRING",
    product_type: "Home > Diamond",
    sale_price_usd: 224.3,
    status: "Active",
    sub_account: "[tanishq]",
    subcategories: "Diamond",
    trendrank: null,
    unit: "",
    updated: false,
    url:
      "/product/tanishq-18kt-yellow-gold-diamond-and-tsavorite-stud-earrings-with-paisley-design-502014sgkaga32",
    variants:
      "{u'2JA005102': {u'price': 15918.0, u'listprice': 15918.0}, u'2JA005103': {u'price': 15990.0, u'listprice': 15990.0}}",
    width: "",
  },
  {
    _id: 240156075988598382210170300994299571518,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819DLVAAA52_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Mia",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573539966000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq 14KT Yellow Gold Drop Down Earrings for Women with Petal Charms",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 10,
    expiration_date: "NA",
    full_description:
      "For the Love of Diamonds  - The exquisitely crafted pear-cut diamonds in the studs spin a beautiful tale of sophistication. The petal charm suspended through a delicate link chain is also embellished with shiny diamonds in intriguing patterns. Sunshine for your Ears  - Sprinkled with beautifully cut diamonds, these gold earrings engage in a magical play of reflections as soon as one puts them on.Comfortable and Secure  - The borderline statement earrings are very comfortable and do not cause irritation when worn for long durations and feature also feature a screw back post clasp to provide a secure fit.  Make an entrance with these super-luxury 14kt gold earrings set from the Mia by Tanishq collection for women. These magnificent earrings are sure to turn some heads as you complete your evening pastel moment by matching them with your outfit. Mia by Tanishq brings another collection of modern jewellery in graceful designs with a pinch of opulence that will accent both, formal and informal looks. With an intent to reflect the beauty, confidence, and inspiring personalities of todays women, these designs are given fetching bold details. Polished in 14KT gold and decorated with gemstones, the jewellery pieces in the Electrify Collection of Mia make a must-have versatile selection that can be worn to a variety of big or small occasions. Please note our products are a result of free-flowing design and are not restricted by the weight of metal and stones, hence the metal and stone weights indicated are not valid.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "30.5 mm",
    id: "552819DLVAAA522BD000181",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819DLVAAA52_1.jpg",
    item_group_id: "552819DLVAAA52_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986550000,
    listprice: 44999,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "552819DLVAAA52",
    mpn: "552819DLVAAA522BD000181",
    name:
      "Mia by Tanishq 14KT Yellow Gold Drop Down Earrings for Women with Petal Charms",
    occasion: "",
    out_of_shelf: false,
    price: 40499,
    price_usd: 632.72,
    product: "DROP EARRING",
    product_type: "Home > Jewellery",
    sale_price_usd: 569.45,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/drop-earring-552819dlvaaa52",
    variants:
      "{u'2BD000181': {u'price': 40499.0, u'listprice': 44999.0}, u'2BD000095': {u'price': 40499.0, u'listprice': 44999.0}}",
    width: "17.1 mm",
  },
  {
    _id: 70708346680285330157272056032104910472,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552811SSNABA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-category",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573539967000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Gold Diamond Drop Earrings",
    diamond_clarity: "SI2",
    diamond_color: "I J",
    diamond_cut: "Round Brilliant Cut",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "This pair of 14KT yellow gold stud earrings features a total of fourteen round brilliant cut diamonds. All diamonds have the quality attributes of SI2 clarity and I-J colour grade. The design is a variation of a six-petal floral motif with openwork detailing. The centre highlights a floral element with seven diamonds in shared prong settings. This earring pair is fitted with screw posts and secured by Bombay screw nuts for a comfortable wear. They feature a high-polished surface finish, and all prong settings are rhodium-plated to enhance the white appearance of the diamonds.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "12.94 mm",
    id: "552811SSNABA223IA506546",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552811SSNABA22_1.jpg",
    item_group_id: "552811SSNABA22_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986552000,
    listprice: 18999,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "552811SSNABA22",
    mpn: "552811SSNABA223IA506546",
    name:
      "Mia by Tanishq Friends of Bride 14KT Yellow Gold Diamond Stud Earrings with Floral Design And Openwork",
    occasion: "",
    out_of_shelf: false,
    price: 18049,
    price_usd: 267.14,
    product: "STUD EARRING",
    product_type: "Home > Jewellery",
    sale_price_usd: 253.78,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: 3,
    unit: "",
    updated: false,
    url: "/product/stud-earring-552811ssnaba22",
    variants:
      "{u'3IA506540': {u'price': 18049.0, u'listprice': 18999.0}, u'3IA506546': {u'price': 18049.0, u'listprice': 18999.0}}",
    width: "12.18 mm",
  },
  {
    _id: 156747118664047959518572843972141932432,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/A14019PCEAAA88_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Silver",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573539968000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq Silver Pendant for Women in Sea Shell Design Embellished with Open Polki",
    diamond_clarity: "",
    diamond_color: "",
    diamond_cut: "",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "Stunning Polki Detail - This pendant is embellished with open polki diamonds at the centre. Unique and Versatile - Its sea shell design has both contemporary and tribal appeal, thus can be mixed and matched with a variety of jewellery to create different looks. Exotic Looking - The swirling pattern and complementing colour palette give this pendant an exotic look, perfect for parties and beach outings. Silver Finished - The pendant also owes its shine to the pure silver polish. Mia Tanishq Jewellery - Crafted by Mia, this pure silver sea shell pendant assures quality and authenticity. Adorn your outfit with authentic silver and diamond jewellery. Designed with polki diamonds in swirling fashion at the centre, this Mia pendant looks stunning. Its ornate design is reminiscent of beautiful sea shells. The swirls and multicolour decoration add more beauty to its simple design. This polki pendant can be worn with a silver rope chain or black choker necklace to create different looks. It is a small, everyday kind of jewellery which you can wear with jumpsuits and feminine blouses. Mia by Tanishq brings another collection of modern jewellery in stunning party designs that will completely make your evening outfit a total head turner. They are meant for the modern women who are outgoing, bold, and fun. All the designs are finished niftily in 92.5 silver, making the articles in Sassy Silver Collection lustrous, easy to care, and lighter on the pocket.",
    gemstone1: "Cubic Zirconia|6|NA|Faceted|Round",
    gemstone2: "Cubic Zirconia|4|NA|Faceted|Round",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 93,
    google_product_category:
      "Apparel & Accessories > Jewelry > Charms & Pendants ",
    gtin: "",
    height: "25.6 mm",
    id: "A14019PCEAAA881BA000003",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/A14019PCEAAA88_1.jpg",
    item_group_id: "A14019PCEAAA88_P",
    jew_size: "",
    jewellery_type: "Silver Jewellery",
    last_modified_on: 1576986546000,
    listprice: 3999,
    metal: "Silver",
    metal_color: "Silver",
    mfr_code: "A14019PCEAAA88",
    mpn: "A14019PCEAAA881BA000003",
    name:
      "Mia by Tanishq Silver Pendant for Women in Sea Shell Design Embellished with Open Polki",
    occasion: "Daily Wear",
    out_of_shelf: false,
    price: 3799,
    price_usd: 56.23,
    product: "PENDANT",
    product_type: "Home > Silver > Sassysilver",
    sale_price_usd: 53.42,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Sassysilver",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/pendant-a14019pceaaa88",
    variants: "{u'1BA000003': {u'price': 3799.0, u'listprice': 3999.0}}",
    width: "29.6 mm",
  },
  {
    _id: 120666785972828418007351627840202950059,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552811VVR1A22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-category",
    collection: "Social at Work",
    color: "",
    condition: "NEW",
    created_on: 1573539968000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Yellow Gold Diamond Bangle",
    diamond_clarity: "SI2",
    diamond_color: "I J",
    diamond_cut: "Round Brilliant Cut",
    discount_percentage: 10,
    expiration_date: "NA",
    full_description:
      "This 14KT yellow gold bangle contains fifteen round brilliant cut diamonds that fall within the I-J colour range and SI2 clarity grade. The bangle features a stylized loop-and-hook design with a diamond-studded drop-shaped element at the centre. The rigid top portion of the bangle is continued with a flexible chain element at the bottom, hence making this wrist wear a combination between a bangle and a flexible bracelet. The diamonds are set in a rhodium-plated, pave-set, drop-shaped element. The banglet is provided with a lobster clasp and O-rings for size adjustment and fastening purpose. A high-polished finish ensures that the banglet appears lustrous.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "47 mm",
    id: "552811VVRE1A223IH000560",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552811VVR1A22_1.jpg",
    item_group_id: "552811VVR1A22_P",
    jew_size: "47 x 57 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986546000,
    listprice: 34999,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "552811VVRE1A22",
    mpn: "552811VVRE1A223IH000560",
    name:
      "Mia by Tanishq 14KT Yellow Gold Diamond Bangle with Interlock Design",
    occasion: "",
    out_of_shelf: false,
    price: 31499,
    price_usd: 492.11,
    product: "BANGLES",
    product_type: "Home > Jewellery",
    sale_price_usd: 442.9,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/bangles-552811vvr1a22",
    variants:
      "{u'3IH000560': {u'price': 31499.0, u'listprice': 34999.0}, u'3IH000500': {u'price': 31499.0, u'listprice': 34999.0}}",
    width: "57 mm",
  },
  {
    _id: 240695356876159612067390605409713517473,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819FTDAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Collections",
    collection: "Smolitaires",
    color: "",
    condition: "NEW",
    created_on: 1573540035000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq 14KT Yellow Gold Ring for Women in ThreePetal Flower Windmill Design",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 7,
    expiration_date: "NA",
    full_description:
      "14KT Gold Ring - This ring is polished with 14KT yellow gold for a semi luxurious finish. Diamond Embellished - Complementing the lustre of gold is the glint of a round cut diamond at the top. Slender Profile - This beautiful floral diamond ring has a slim silhouette that is comfortable to wear for hours. Mia Tanishq Jewellery - Made by Tanishq, this Mia ring is impressive in quality and design. Beautiful Gift - This ring will make a pretty gift for any woman, be it your mother, wife, or daughter. This fancy accessory is crafted with flower windmill design for a modern look that goes with most outfits. This finger ring for women comes polished in 14KT yellow gold for an eye catching flair. Complementing this golden lustre is the glint of a round cut diamond that sits in the crown. Secured by prong setting, the solitaire adds an attractive glint to the ring. Beautiful and luxurious, this gold diamond ring make a memorable gift. Versatile design makes the ring a practical piece of everyday jewellery for women. Mia by Tanishq brings another collection of modern jewellery in versatile ethno contemporary designs that complete both, formal and informal looks. They are meant for the modern women who are powerful, strong, and charming. All the designs are crafted niftily in 14KT gold, making the articles in Smolitaire Collection dazzling, easy to care, and lighter on the pocket.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "22.69 mm",
    id: "552819FTDNAA222BD000126",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819FTDAA22_1.jpg",
    item_group_id: "552819FTDAA22_P",
    jew_size: "17.20 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986557000,
    listprice: 20999,
    metal: "Gold",
    metal_color: "yellow",
    mfr_code: "552819FTDNAA22",
    mpn: "552819FTDNAA222BD000126",
    name:
      "Mia by Tanishq 14KT Yellow Gold Ring for Women in ThreePetal Flower Windmill Design",
    occasion: "",
    out_of_shelf: false,
    price: 19529,
    price_usd: 295.26,
    product: "FINGER RING",
    product_type: "Home > Collections > Smolitaires",
    sale_price_usd: 274.59,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Smolitaires",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-552819ftdaa22",
    variants:
      "{u'2BD000100': {u'price': 19529.0, u'listprice': 20999.0}, u'2BD000126': {u'price': 19529.0, u'listprice': 20999.0}}",
    width: "20.49 mm",
  },
  {
    _id: 200661449920094304610063044078945684309,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819FRVAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Collections",
    collection: "Smolitaires",
    color: "",
    condition: "NEW",
    created_on: 1573540037000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq 14KT Yellow Gold Ring for Women with Studded Diamond",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "Solitaire Ring - This finger ring for women comes embellished with a single diamond in the crown in a prong setting. 14KT White Gold Finish - This sparkling diamond ring comes finished in 14KT white gold for added opulence. Gold Ring for Daily Use - Despite the diamond studded design, the ring is a pretty selection to wear every day. It can be worn to office as well. Comfortable to Wear - Soft curves and smooth touch let you glide it in and out of the finger without any discomfort. Mia Tanishq Jewellery - The diamond and gold ring for women is a part of the Smolitaire Collection of Mia by Tanishq. This piece of gold jewellery is an accessory you can wear every day. Designed for the modern day women, this ring has a stylish appeal without any extravagant details. The 14KT gold finish of this finger ring for women combines with the sparkling diamond in the crown to create a prepossessing visual effect. The wavy detail on both the sides of the diamond gives this ring a fancier look, while the traditional round band makes its design timeless. This gold diamond ring is a go to accessory whether you are dressing up or down. Mia by Tanishq brings another collection of modern jewellery in versatile ethno contemporary designs that complete both, formal and informal looks. They are meant for the modern women who are powerful, strong, and charming. All the designs are crafted niftily in 14KT gold, making the articles in Smolitaire Collection dazzling, easy to care, and lighter on the pocket",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "22.31 mm",
    id: "552819FRVLAA222BD000002",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819FRVAA22_1.jpg",
    item_group_id: "552819FRVAA22_P",
    jew_size: "16.40 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986560000,
    listprice: 17999,
    metal: "Gold",
    metal_color: "yellow",
    mfr_code: "552819FRVLAA22",
    mpn: "552819FRVLAA222BD000002",
    name: "Mia by Tanishq 14KT Yellow Gold Ring for Women with Studded Diamond",
    occasion: "",
    out_of_shelf: false,
    price: 17099,
    price_usd: 253.08,
    product: "FINGER RING",
    product_type: "Home > Collections > Smolitaires",
    sale_price_usd: 240.42,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Smolitaires",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-552819frvaa22",
    variants: "{u'2BD000002': {u'price': 17099.0, u'listprice': 17999.0}}",
    width: "19.97 mm",
  },
  {
    _id: 328766844116160336581210113230513623850,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552811DYWAAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-category",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573540037000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Yellow Gold Diamond Drop Earrings",
    diamond_clarity: "SI2",
    diamond_color: "I J",
    diamond_cut: "Round Brilliant Cut",
    discount_percentage: 7,
    expiration_date: "NA",
    full_description:
      "This pair of 14KT yellow gold drop earrings is composed of three parts: a diamond stud, a diamond-studded teardrop-shaped element with a central negative space and a larger teardrop element with openwork. The three parts are detachable and are placed one after the other respectively, along the screw post. The earrings contain twenty-four round brilliant cut diamonds in total, all of which fall within the I-J colour range and SI2 clarity grade. While the diamond stud contains a single diamond set in a rhodium-plated four prong setting, the smaller teardrop element showcases diamonds set in rhodium-plated shared prong settings. A high-polished finish renders an attractive appeal to these earrings. The earrings are secured by Bombay screw closures.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "12.44 mm",
    id: "552811DYWAAA223IA006038",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552811DYWAAA22_1.jpg",
    item_group_id: "552811DYWAAA22_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986559000,
    listprice: 29999,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "552811DYWAAA22",
    mpn: "552811DYWAAA223IA006038",
    name:
      "Mia by Tanishq 14KT Yellow Gold Diamond Drop Earrings with Teardrop Design",
    occasion: "",
    out_of_shelf: false,
    price: 27899,
    price_usd: 421.81,
    product: "DROP EARRING",
    product_type: "Home > Jewellery",
    sale_price_usd: 392.28,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/drop-earring-552811dywaaa22",
    variants:
      "{u'2JA001024': {u'price': 27899.0, u'listprice': 29999.0}, u'2JA001026': {u'price': 27899.0, u'listprice': 29999.0}, u'3IA006038': {u'price': 27899.0, u'listprice': 29999.0}}",
    width: "10.02 mm",
  },
  {
    _id: 132057439227925060736598545859637958224,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552812HQUAAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-category",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573540037000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "14KT Diamond Oval Hoops",
    diamond_clarity: "SI2",
    diamond_color: "I J",
    diamond_cut: "Round Brilliant Cut",
    discount_percentage: 7,
    expiration_date: "NA",
    full_description:
      "This pair of 14KT yellow gold hoop earrings features twenty-six round brilliant cut diamonds that fall within the SI2 clarity and I-J colour range. Each earring showcases a rhodium-plated hoop element, accentuated with pave-set diamonds. Three oval elements in a combination of rose gold plating, white rhodium plating and yellow gold are suspended form the lower part of the hoop design. The yellow gold oval element is formed by polished, mini, gold beads. Fitted with silicone rubber bushings, these earrings look shiny. You will surely look stunning with this pair of earrings on you while at work.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "21.09 mm",
    id: "552812HQUAAA223IA005576",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552812HQUAAA22_1.jpg",
    item_group_id: "552812HQUAAA22_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986573000,
    listprice: 23999,
    metal: "Gold",
    metal_color: "Tri Colour",
    mfr_code: "552812HQUAAA22",
    mpn: "552812HQUAAA223IA005576",
    name:
      "Mia All-Rounders by Tanishq 14KT Yellow Gold Diamond Hoop Earrings with Oval Design",
    occasion: "",
    out_of_shelf: false,
    price: 22319,
    price_usd: 337.44,
    product: "HOOP EARRING",
    product_type: "Home > Jewellery",
    sale_price_usd: 313.82,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: 1,
    unit: "",
    updated: false,
    url: "/product/hoop-earring-552812hquaaa22",
    variants:
      "{u'3IA000505': {u'price': 22319.0, u'listprice': 23999.0}, u'3IA005576': {u'price': 22319.0, u'listprice': 23999.0}, u'3IA005563': {u'price': 22319.0, u'listprice': 23999.0}}",
    width: "10.89 mm",
  },
  {
    _id: 219363251782395865772532020571397922062,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552819FTAAA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Collections",
    collection: "Smolitaires",
    color: "",
    condition: "NEW",
    created_on: 1573540038000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description: "Mia by Tanishq 14KT Yellow Gold Ring for Women",
    diamond_clarity: "SI2",
    diamond_color: "I;J",
    diamond_cut: "Ideal",
    discount_percentage: 7,
    expiration_date: "NA",
    full_description:
      "Simple Everyday Ring - This ring is designed without extravagant details, thus, making it a great selection as an everyday jewellery for women. Opulent Gold Finish - The ladies ring comes finished in a shiny 14KT gold polish. Diamond Embellished - Adding a sparkle to this 14KT gold ring is a round cut diamond on the top. Comfortable to Wear - Its smooth curves glide and sit gently on the finger, causing no discomfort. Versatile Design - This gold diamond ring will complement your everyday outfits, be it ethnic, formal, informal, or western. This stunning finger ring for women comes in a contemporary design. Infinity gold polished band with embellishing diamond at the centre top create an attractive appeal. Apart from being imposing, the ring is extremely versatile. It can be worn with a variety of clothes like ethnic or western, to create fetching ensembles. The modest design makes it a fitting choice as diamond and gold ring for daily use. This gold diamond ring is a pretty gift to present someone on occasions. Mia by Tanishq brings another collection of modern jewellery in versatile ethno contemporary designs that complete both, formal and informal looks. They are meant for the modern women who are powerful, strong, and charming. All the designs are crafted niftily in 14KT gold, making the articles in Smolitaire Collection dazzling, easy to care, and lighter on the pocket",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 14,
    google_product_category: "Jewellery",
    gtin: "",
    height: "20.42 mm",
    id: "552819FTAMAA222BD000041",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552819FTAAA22_1.jpg",
    item_group_id: "552819FTAAA22_P",
    jew_size: "16.80 mm",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986549000,
    listprice: 24999,
    metal: "Gold",
    metal_color: "yellow",
    mfr_code: "552819FTAMAA22",
    mpn: "552819FTAMAA222BD000041",
    name: "Mia by Tanishq 14KT Yellow Gold Ring for Women",
    occasion: "",
    out_of_shelf: false,
    price: 23249,
    price_usd: 351.5,
    product: "FINGER RING",
    product_type: "Home > Collections > Smolitaires",
    sale_price_usd: 326.9,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Smolitaires",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-552819ftaaa22",
    variants:
      "{u'2BD000041': {u'price': 23249.0, u'listprice': 24999.0}, u'2BD000035': {u'price': 23249.0, u'listprice': 24999.0}}",
    width: "22.98 mm",
  },
  {
    _id: 36068800877749793860753615091129393143,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/A14019FCEAA88_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "Silver",
    collection: "Sassy Silver",
    color: "",
    condition: "NEW",
    created_on: 1573540038000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Mia by Tanishq Silver Ring for Women in Sea Shell Design Embellished with Open Polki",
    diamond_clarity: "",
    diamond_color: "",
    diamond_cut: "",
    discount_percentage: 5,
    expiration_date: "NA",
    full_description:
      "Distinguished Design - This Mia silver ring comes in a unique sea shell design that is meant to stand out. 92.5 Sterling Silver - Finished with pure silver, this ladies ring is a luxurious and shiny piece of jewellery to add to your collection. Open Polki Ring - Embellished with uncut diamonds in a swirling and round fashion, it features a lovely polki design. Comfortable to Wear - This silver ring for women is smooth at touch and causes no discomfort whether worn for an hour or a day. Easy to Care - Proper storage in a tarnish-preventive bag and preventing exposure to salt, household chemicals, and chlorinated water is all it needs. This lovely Mia ring flaunts lustrous silver finish and the glimmer of polki diamonds. This finger ring for women has a unique design that is embellished with multicolour details. Reminiscent of the sea shells, the ring is timeless in appeal. Its feminine appeal is highlighted by the slender band, that glides softly against the skin without causing discomfort. Wear this Mia Tanishq jewellery to complete your party and dinner outfits. Complement it with matching pendant necklace and earrings by Tanishq. Mia by Tanishq brings another collection of modern jewellery in stunning party designs that will completely make your evening outfit a total head turner. They are meant for the modern women who are outgoing, bold, and fun. All the designs are finished niftily in 92.5 silver, making the articles in Sassy Silver Collection lustrous, easy to care, and lighter on the pocket.",
    gemstone1: "Cubic Zirconia|11|NA|Faceted|Round",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "",
    goldkaratage: 93,
    google_product_category: "Jewellery",
    gtin: "",
    height: "10.5 mm",
    id: "A14019FCELAA881BA000004",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/A14019FCEAA88_1.jpg",
    item_group_id: "A14019FCEAA88_P",
    jew_size: "16.40 mm",
    jewellery_type: "Silver Jewellery",
    last_modified_on: 1576986571000,
    listprice: 3999,
    metal: "Silver",
    metal_color: "Silver",
    mfr_code: "A14019FCELAA88",
    mpn: "A14019FCELAA881BA000004",
    name:
      "Mia by Tanishq Silver Ring for Women in Sea Shell Design Embellished with Open Polki",
    occasion: "Daily Wear",
    out_of_shelf: false,
    price: 3799,
    price_usd: 56.23,
    product: "FINGER RING",
    product_type: "Home > Silver > Sassysilver",
    sale_price_usd: 53.42,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Sassysilver",
    trendrank: null,
    unit: "",
    updated: false,
    url: "/product/finger-ring-a14019fceaa88",
    variants: "{u'1BA000004': {u'price': 3799.0, u'listprice': 3999.0}}",
    width: "23.9 mm",
  },
  {
    _id: 278848509799827500226248461091058054976,
    additional_image:
      "https://staticimg.titan.co.in/Mia/Catalog/552817NHKLA22_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "MIA",
    business_unit: "Jewellery",
    category: "tq-mia-category",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573540038000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "V Day Collection from Mia by Tanishq 14KT White Gold Diamond Neckwear",
    diamond_clarity: "SI2",
    diamond_color: "I J",
    diamond_cut: "Round Brilliant Cut",
    discount_percentage: 20,
    expiration_date: "NA",
    full_description:
      "Bringing together a pair of interlocked hearts, this neckwear symbolises boundless love forever. Crafted to perfection with 14KT white and rose gold, the pendant stands elite with the brilliance of round cut diamonds.",
    gemstone1: "",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 14,
    google_product_category: "Apparel & Accessories > Jewelry > Necklaces",
    gtin: "",
    height: "",
    id: "552817NHKFLA222JA005102",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Mia/Catalog/552817NHKLA22_1.jpg",
    item_group_id: "552817NHKLA22_P",
    jew_size: "",
    jewellery_type: "Diamond Jewellery",
    last_modified_on: 1576986561000,
    listprice: 19999,
    metal: "Gold",
    metal_color: "Bi Color",
    mfr_code: "552817NHKFLA22",
    mpn: "552817NHKFLA222JA005102",
    name:
      "V-Day Collection from Mia by Tanishq 14KT White Gold Diamond Neckwear",
    occasion: "",
    out_of_shelf: false,
    price: 15999,
    price_usd: 281.2,
    product: "NECKLACE",
    product_type: "Home > Jewellery",
    sale_price_usd: 224.96,
    status: "Active",
    sub_account: "[tanishq, mia]",
    subcategories: "Jewellery",
    trendrank: 2,
    unit: "",
    updated: false,
    url: "/product/necklace-552817nhkla22",
    variants:
      "{u'2JA000116': {u'price': 18999.0, u'listprice': 19999.0}, u'2JA000171': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000173': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000204': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000264': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000203': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000077': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000269': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000246': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000245': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000190': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000256': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000109': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000126': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000025': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000235': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000234': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000217': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000216': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000089': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000279': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000160': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000272': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000271': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000168': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA005102': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000283': {u'price': 15999.0, u'listprice': 19999.0}, u'2JA000280': {u'price': 15999.0, u'listprice': 19999.0}}",
    width: "440 mm",
  },
  {
    _id: 224997284018995584214827302468160917392,
    additional_image:
      "https://staticimg.titan.co.in/Tanishq/Catalog/501032DHAABA18_2.jpg",
    adult: "No",
    availability_date: "NA",
    avlble: 1,
    brand: "Tanishq",
    business_unit: "Jewellery",
    category: "Jeweller",
    collection: "",
    color: "",
    condition: "NEW",
    created_on: 1573540038000,
    currency: "INR",
    currency_symbol: "&#8377;",
    description:
      "Floral Drop Earrings set in 18KT Yellow Gold and studded with Marquise Pear and Round Rubies",
    diamond_clarity: "",
    diamond_color: "",
    diamond_cut: "",
    discount_percentage: 0,
    expiration_date: "NA",
    full_description:
      "These ruby drop earrings inspired by floral patterns will elevate the elegance of your traditional ensembles. Save this pair for special occasions.",
    gemstone1: "Ruby|20|Prong|NA|Marquise,Pear,Round",
    gemstone2: "",
    gemstone3: "",
    gemstone4: "",
    gemstone5: "",
    gender: "Female",
    goldkaratage: 18,
    google_product_category: "Apparel & Accessories > Jewelry",
    gtin: "",
    height: "",
    id: "501032DHAABA182BA000063",
    identifier_exists: false,
    image: "https://staticimg.titan.co.in/Tanishq/Catalog/501032DHAABA18_1.jpg",
    item_group_id: "501032DHAABA18_P",
    jew_size: "",
    jewellery_type: "Coloured Stone Jewellery",
    last_modified_on: 1576825198000,
    listprice: 18432,
    metal: "Gold",
    metal_color: "Yellow",
    mfr_code: "501032DHAABA18",
    mpn: "501032DHAABA182BA000063",
    name: "Kumuda Ruby Drop Earrings",
    occasion: "Traditional Wear",
    out_of_shelf: false,
    price: 18432,
    price_usd: 279.49,
    product: "DROP EARRING",
    product_type: "Home > Jeweller > Greatdiamondsale",
    sale_price_usd: 279.49,
    status: "Active",
    sub_account: "[tanishq]",
    subcategories: "Greatdiamondsale",
    trendrank: null,
    unit: "",
    updated: false,
    url:
      "/product/tanishq-18kt-yellow-gold-and-diamond-drop-earring-501032dhaaba18",
    variants:
      "{u'2BA000063': {u'price': 19925.0, u'listprice': 19925.0}, u'2BA000061': {u'price': 18432.0, u'listprice': 18432.0}}",
    width: "",
  },
];
